inner dist

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,6 +12,7 @@ jobs:
       pages: write
       id-token: write
     
+    
     steps:
       - uses: actions/checkout@v3
         
@@ -30,7 +31,7 @@ jobs:
           node-version: '18'
 
       - name: Install dependencies
-        run: npm ci
+        run: npm ci|| (echo "npm ci failed!" && exit 1)
 
       - name: Build
         run: |
@@ -40,7 +41,7 @@ jobs:
           echo "Build finished."
           echo "Checking dist directory..."
           ls -R dist || (echo "Dist directory not found!" && exit 1)
-      
+
 
       - name: Verify build output
         run: |
